spring:
  datasource:
    url: jdbc:mysql://localhost:3307/vhr3?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true  # 启用 JPA SQL 日志输出
#    properties:
#      hibernate:
#        format_sql: true  # 格式化 SQL 日志
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#
#logging:
#    level:
#      org.hibernate.SQL: DEBUG  # JPA SQL 日志
#      org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # JPA 参数日志
#      org.apache.ibatis: DEBUG  # MyBatis 日志（如果使用 MyBatis）
#      org.springframework: INFO  # Spring 框架日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#      com.example.vhr4: DEBUG  # 项目日志（根据你的包名调整）